### ISSUE TITLE
Argument Inversion for Update-method

### ISSUE THREAD

**Issue by LudoDaemen** [goulart-paul/osqp-r#1]
There is a small mistake in the Update-method of the osqp-object : the l and u arguments are swapped ... causing an update of the upper bound to affect the lower bound (and vice versa)

We have in line 128 of osqp.R :
    osqpUpdate(private$.work, q, u, l)
which should rather become 
    osqpUpdate(private$.work, q, l, u)
It seems that the downstream code for osqpUpdate assumes indeed that the lower-bound precedes the upper bound.

**Comment by goulart-paul** [comment]
Thanks.   It is fixed here: b0c8ccea81dab67c870e25dee21a1f2dbc461f59
