### ISSUE TITLE
osqp package installation failed on CRAN

### ISSUE THREAD

**Issue by ngreifer** [goulart-paul/osqp-r#10]
`osqp` failed the automatic [CRAN checks](https://cran.r-project.org/web/checks/check_results_osqp.html), which has been some trouble for my package `optweight` that depends on it. Is there a timeline for this being fixed so I can keep my package on CRAN, or should I change the dependency to another optimization package (e.g., `rosqp`, the old version) until this is fixed?

**Comment by bstellato** [comment]
In the next couple of weeks, we are releasing the next version `0.6.0` which should fix the issue. We tried to message the CRAN maintainers about the solaris problem (which, by the way, affects many other packages) but we did not get any reply. This PR https://github.com/oxfordcontrol/osqp/pull/164 should fix the issue.

**Comment by ngreifer** [comment]
Thank you!

**Comment by goulart-paul** [comment]
This is now fixed with release of 0.6.0.2 on CRAN.
