### ISSUE TITLE
Inconsistency between version of python and R OSQP

### ISSUE THREAD

**Issue by dkang9503** [goulart-paul/osqp-r#14]
Hello,

We we were working on the CVXR package and noticed an inconsistency in a solution output for the osqp solver

Here is a reproducible example for both R and Python

```
library(osqp)
library(Matrix)

P <- sparseMatrix(i=1, j=1, x = 0)
q <- 1
A <- sparseMatrix(i=c(1,2), j=c(1,1), x = c(-1.0, 1.0))
lA <- c(-Inf, -Inf)
uA <- c(-1., 0.)
solver_opts <- list()
solver_opts$eps_abs <- 1e-5
solver_opts$eps_rel <- 1e-5
solver_opts$max_iter <- 10000
solver_opts$polish <- TRUE

model <- osqp::osqp(P, q, A, lA, uA, solver_opts)
result <- model$Solve()

print(result$x) #It's .5 when it should be infeasible
#Should be infeasible but it reaches max iter instead. Status code -2
print(result$info$status_val) 
```

```
import scipy.sparse as sp
import numpy as np
import osqp

P = sp.csc_matrix([0])
q = np.array([1.])
A = sp.vstack([-1.0, 1.0]).tocsc()
lA = np.array([-np.inf, -np.inf])
uA = np.array([-1., 0.])
solver_opts = {
    "eps_abs" : 1e-5,
    "eps_rel" : 1e-5,
    "max_iter" : 10000,
    "polish": True
}

solver = osqp.OSQP()
solver.setup(P, q, A, lA, uA, verbose=True, **solver_opts)
results = solver.solve()

print(results.x) #None
print(results.info.status_val) #Primal infeasible

```

Thanks so much!

**Comment by goulart-paul** [comment]
I observe the same issue.  It doesn't appear to be related to the version, since the solver returns an infeasible status (i.e. the correct behaviour) for me in both 0.6.0 (matlab interface) and 0.5.0 (python interface).   I get termination after the maximum iteration limit in R (v0.6.0).

Which version of the R interface are you using?

**Comment by goulart-paul** [comment]
The problem appears to be that the line `lA <- c(-Inf, -Inf)` is not internally converted to (negative)`OSQP_INFTY` values within the R interface.   Changing that line to `lA <- c(-1e30, -1e30)` produces the same behaviour as the python interface.

I will make a fix for this as soon as I can, but we will first clarify in the osqp main project where the responsibility for catching `inf` values lies when calling the solver via an external language interface.
