### ISSUE TITLE
please upgrade to new osqp

### ISSUE THREAD

**Issue by tdhock** [goulart-paul/osqp-r#39]
hi @bnaras!
I'm having an installation issue with the current R package release, which could be fixed by upgrading your osqp submodule to the newest version. Could you do that please?

The current/old version from https://github.com/osqp/osqp/blob/0dd00a578cf1c2691c5c379965d504c75bf6cfad/configure/cmake/FindR.cmake#L10C34-L11C35 is 

```
find_program(R_EXEC NAMES R R.exe)
```
which causes an issue for my installation, because it does not search the R_HOME first, https://github.com/tdhock/data.table-revdeps/issues/3

The new version in https://github.com/osqp/osqp/blob/master/configure/cmake/FindR.cmake#L11 has
```
find_program(R_EXEC NAMES R Rdev R.exe HINTS ENV R_HOME /opt/R-devel PATH_SUFFIXES bin)
```
which fixes my issue because the HINTS tells it to search R_HOME before looking on PATH.

**Comment by bnaras** [comment]
Thanks @tdhock. Yes, this is due to the finding R part that I patched up myself for CRAN before I noticed that osqp had a newer version.  Will fix.

**Comment by bnaras** [comment]
@tdhock The current version on CRAN avoids use of `cmake` and so should not have this issue. So may I close this?

**Comment by tdhock** [comment]
yes thanks!
