### ISSUE TITLE
Problem installing package on RedHat 8 system, R 4.4.0

### ISSUE THREAD

**Issue by ammadore** [goulart-paul/osqp-r#40]
Hi, I am guetting error installing the latest version of osqp on R4.4.0 using R CMD INSTALL that indicate problems with CMakeList.txt files and include directories. I don't know how to correct the problem. Just to say, I also tried the installation with install.packages as well as with remotes::install_git() from within RStudio as proposed in the OSQP user documentation and none of them have worked. Here is the log of my last try using R CMD INSTALL:

[ammadore@dsf-cobraa R]$ /opt/R/4.4.0/bin/R CMD INSTALL osqp-r.tar.gz 
* installing to library ‘/home/ammadore/R/x86_64-pc-linux-gnu-library/4.4’
* installing *source* package ‘osqp’ ...
** using staged installation
++ : /opt/R/4.4.0/lib/R
++ test -z /opt/R/4.4.0/lib/R
+++ /opt/R/4.4.0/lib/R/bin/R CMD config CC
++ CC=gcc
+++ /opt/R/4.4.0/lib/R/bin/R CMD config CFLAGS
++ CFLAGS='-g -O2'
+++ /opt/R/4.4.0/lib/R/bin/R CMD config CPPFLAGS
++ CPPFLAGS=-I/usr/local/include
+++ /opt/R/4.4.0/lib/R/bin/R CMD config CXX
++ CXX='g++ -std=gnu++17'
+++ /opt/R/4.4.0/lib/R/bin/R CMD config CXXFLAGS
++ CXXFLAGS='-g -O2'
+++ /opt/R/4.4.0/lib/R/bin/R CMD config LDFLAGS
++ LDFLAGS=-L/usr/local/lib
+++ command -v cmake
++ '[' -x /bin/cmake ']'
++ echo 'Making fixes to osqp_sources for CRAN'
Making fixes to osqp_sources for CRAN
++ cd src
++ /opt/R/4.4.0/lib/R/bin/Rscript ../inst/58f00bd_fixes/make_fixes.R
[1] TRUE
++ echo '-- Trying to build libosqp.a via cmake ...'
-- Trying to build libosqp.a via cmake ...
++ cd src/osqp_sources
++ mkdir -p build
++ cd build
++ cmake -DR_HOME=/opt/R/4.4.0/lib/R -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS:bool=OFF -DCMAKE_POSITION_INDEPENDENT_CODE:bool=ON -DR_LANG=TRUE -DCMAKE_INSTALL_PREFIX:PATH=../../ ..
-- The C compiler identification is GNU 8.5.0
-- The CXX compiler identification is GNU 8.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- We are on a Linux system
-- Embedded is OFF
-- Printing is ON
-- Profiling is ON
-- User interrupt is ON
-- Floats are OFF
-- Long integers (64bit) are ON
-- Code coverage is OFF
-- MKL Pardiso: ON
-- We are building the R interface
-- R exec is: /usr/local/bin/R
-- R root dir is: WARNING: ignoring environment value of R_HOME
/opt/R/4.3.0/lib64/R
-- R includes are in: R_INCLUDE_DIRS-NOTFOUND
-- Floats are OFF
-- Long integers (64bit) are ON
-- Configuring done (0.8s)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
R_INCLUDE_DIRS (ADVANCED)
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys/direct
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys/direct
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys/direct
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys/direct
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys/direct
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys/direct
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys/direct
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys/direct/qdldl
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys/direct/qdldl
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys/direct/qdldl
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys/direct/qdldl
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys/direct/qdldl
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys/direct/qdldl
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys/direct/qdldl
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys/direct/qdldl/qdldl_sources
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys/direct/qdldl/qdldl_sources
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys/direct/qdldl/qdldl_sources
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys/direct/qdldl/qdldl_sources
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys/direct/qdldl/qdldl_sources
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys/direct/qdldl/qdldl_sources
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys/direct/qdldl/qdldl_sources
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys/direct/qdldl/qdldl_sources
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys/direct/qdldl/qdldl_sources
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys/direct/qdldl/qdldl_sources
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys/direct/qdldl/qdldl_sources
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys/direct/pardiso
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys/direct/pardiso
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys/direct/pardiso
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys/direct/pardiso
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys/direct/pardiso
   used as include directory in directory /tmp/RtmpzNkVnS/R.INSTALL34f4d26e134a2e/osqp-r/src/osqp_sources/lin_sys/direct/pardiso

CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of "osqpstatic":

    "R_INCLUDE_DIRS-NOTFOUND"

CMake Error in lin_sys/direct/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "linsys_pardiso":

    "R_INCLUDE_DIRS-NOTFOUND"

CMake Error in lin_sys/direct/qdldl/CMakeLists.txt:
  Found relative path while evaluating include directories of "linsys_qdldl":

    "R_INCLUDE_DIRS-NOTFOUND"

CMake Error in lin_sys/direct/qdldl/qdldl_sources/CMakeLists.txt:
  Found relative path while evaluating include directories of "qdldlobject":

    "R_INCLUDE_DIRS-NOTFOUND"

CMake Error in lin_sys/direct/qdldl/qdldl_sources/CMakeLists.txt:
  Found relative path while evaluating include directories of "qdldlstatic":

    "R_INCLUDE_DIRS-NOTFOUND"

CMake Error in lin_sys/direct/qdldl/qdldl_sources/CMakeLists.txt:
  Found relative path while evaluating include directories of "qdldl":

    "R_INCLUDE_DIRS-NOTFOUND"

CMake Error in lin_sys/direct/qdldl/qdldl_sources/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "qdldl_example":

    "R_INCLUDE_DIRS-NOTFOUND"

-- Generating done (0.0s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
ERROR: configuration failed for package ‘osqp’
* removing ‘/home/ammadore/R/x86_64-pc-linux-gnu-library/4.4/osqp’

**Comment by bnaras** [comment]
Thank you. This is related to [this other issue.](https://github.com/osqp/osqp-r/issues/40). The underlying cause is that `cmake` is found. I really need to get rid of `cmake` use in the R package since the underlying library is beginning to download submodules during install, a bit of a no-no for CRAN...

A temporary fix is to ensure `cmake` is not found in the path when installing the library. Hacky, I know...

**Comment by bnaras** [comment]
The fix is on on CRAN now and so a reinstall should take care of it.

**Comment by ammadore** [comment]
Thank you very much, I installed it with install.packages and it worked.

**Comment by bnaras** [comment]
Closing issue as completed
