### ISSUE TITLE
what is the format of problem using OSQP-R

### ISSUE THREAD

**Issue by ghost** [goulart-paul/osqp-r#8]
Hi there , How I can find an example to use OSQP in R? which function should I call? what is input order?

**Comment by goulart-paul** [comment]
We are somewhat lacking in examples for the OSQP R interface at present.   However, you might find the unit test helpful : https://github.com/oxfordcontrol/osqp-r/tree/master/tests/testthat

I will leave this open with a view to making some more accessible examples.

**Comment by ghost** [comment]
Thanks for the reply, my data set is very large so making matrix A is expensive even in 32 GB pc. Is there any way to deal with?


Bests
Naghmeh

On Aug 22, 2019, at 3:53 AM, Paul Goulart <notifications@github.com<mailto:notifications@github.com>> wrote:


✉External message: use caution.


We are somewhat lacking in examples for the OSQP R interface at present. However, you might find the unit test helpful : https://github.com/oxfordcontrol/osqp-r/tree/master/tests/testthat

I will leave this open with a view to making some more accessible examples.

**Comment by bstellato** [comment]
The OSQP R reference manual provides the some examples: https://cran.r-project.org/web/packages/osqp/osqp.pdf 

Are you making `A` as dense or sparse? It is better in general to use sparse matrices. How large is it? How many nonzeros? Have you considered using other faster languages? I suggest you to use the [forum](https://osqp.discourse.group/) for this kind of questions.

**Comment by naghmeh6** [comment]
I made my matrix sparse but same error:

ERROR in LDL_factor: Error in KKT matrix LDL factorization when computing the nonzero elements. The problem seems to be non-convex
ERROR in osqp_setup: Linear systems solver initialization failure
Error in osqpSolve(private$.work) : external pointer is not valid

I am sure P is semi definite

**Comment by naghmeh6** [comment]
here is my code 

library(osqp)
library(Matrix)
P1<- matrix(0,18603,18603)
diag(P1[1:21,1:21])<-1
P<- Matrix(P1, sparse=TRUE)
df1<-train[,]
ModeTrain<-df1$MODE
df<-df1[,]
df<-df[,-1]
A<-scale(df)
m2<-data.matrix(A)
dim(m2)
h<-matrix(1, 6194,1)
m2<-cbind(m2,h)
BigKernel<-Matrix::bdiag(replicate(3, m2, simplify = FALSE))
BigKernel<-as.matrix(BigKernel)
Amat<-BigKernel[,]
vec_mode<-ModeTrain
vec_mode<-as.numeric(factor(vec_mode))
library(reshape2)
matr <- matrix(-1, nrow = length(vec_mode), ncol = max(vec_mode))
matr[cbind(seq_along(vec_mode), vec_mode)]<- 1
colnames(matr) <- paste0( seq_len(max(vec_mode)))
Y.long<-melt(matr, id.vars = 1:3)
y<-Y.long[,-1:-2]
Am<-Amat[,]*y
I<- matrix(0,18582 ,18582 )
diag(I) <- 1
A<-cbind(Am,I)
Z<- matrix(0,18582 ,21)
Ep<- matrix(0,18582 ,18582 )
diag(Ep) <- 1
A1<-cbind(Z,Ep)
AA<-rbind(A,A1)
AAS<- Matrix(AA, sparse=TRUE)
w<-matrix(0,21,1)
a<-matrix(10,18582,1)
q<- c(w,a)
u<-rep(c(10), times = 2*18582)
l1<-rep(c(1), times = 18582 )
l2<-rep(c(0), times = 18582 )
l<-c(l1,l2)
settings <- osqpSettings(verbose = TRUE)
res <- solve_osqp(P, q, AAS, l, u, settings)
res$x

P is semi defined so convex why I get error?

**Comment by bstellato** [comment]
I am closing it since the manual should be clear. Feel free to reopen this in case you need further help.
